### ISSUE TITLE
太多冗余标签了

### ISSUE THREAD

**Issue by chokcoco** [hangyangws/baseCss#2]
提点建议，太多冗余标签了。举个例子：
诸如 div 、dt、li 、th、td 等标签在和任何浏览器下都是没有默认 padding 和 margin 的。
那给它都添加上一个全局标签如下是没有意义的。
```CSS
{
    margin: 0;
    padding: 0;
}
```
我们都知道在脚本语言中不要滥用全局变量，避免污染全局环境，却很容易在 CSS 中忽略这一点。
尽量简化你的base.css，只留下必要的，然后根据业务需求修改。
以下面这个为例，
```CSS
img,
abbr,
input,
button,
acronym,
fieldset,
textarea {
    border: none;
}
```
譬如 `abbr`、`acronym`、`fieldset` 可能大部分人甚至都不清楚它的语义，代码中几十个项目都不会出现一次，却被初始化了这么多次，是完全没有必要的。
